name: Pipeline to run tests

on:  
  push:  
    branches:  
      - main 
  pull_request: 
    branches:  
      - main 
  workflow_dispatch:
    inputs:
        browser:
          description: 'Select browser for tests'
          required: true
          default: 'Chrome'
          type: choice
          options:
            - Chrome
            - Firefox
            - Edge
  schedule:
    - cron: '0 14 * * *'

jobs:  
  build:  
    name: Build and test 
    runs-on: ubuntu-latest 
    env:
      BROWSER_TYPE: Chrome   # Default for push/pull_request
    steps: 
    - name: Checkout code 
      uses: actions/checkout@v6 

    - name: Setup .NET 
      uses: actions/setup-dotnet@v5 
      with:  
        dotnet-version: '8.0.x' 
        
    - name: Set browser from workflow_dispatch input
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: echo "BROWSER_TYPE=${{ github.event.inputs.browser }}" >> $GITHUB_ENV
        
    - name: Install Chrome dependencies 
      if: ${{ env.BROWSER_TYPE == 'Chrome' }}
      uses: browser-actions/setup-chrome@v2

    - name: Install Firefox
      if: ${{ env.BROWSER_TYPE == 'Firefox' }}
      uses: browser-actions/setup-firefox@v1

    - name: Install Edge dependencies and Microsoft Edge
      if: ${{ env.BROWSER_TYPE == 'Edge' }}
      uses: browser-actions/setup-edge@v1

    - name: Restore dependencies 
      run: dotnet restore 
      working-directory: .

    - name: Build 
      run: dotnet build --configuration Release --no-restore 
      working-directory: .

    - name: Run API tests
      env:
        BROWSER_TYPE: ${{ github.event.inputs.browser }}
        HEADLESS: 'true'
      run: dotnet test --no-build --configuration Release --verbosity normal --filter "Category=API"
      working-directory: .
      continue-on-error: true
      
    - name: Run other tests
      env:
        BROWSER_TYPE: ${{ github.event.inputs.browser }}
        HEADLESS: 'true'
      run: dotnet test --no-build --configuration Release --verbosity normal --filter "Category!=API"
      working-directory: .
      continue-on-error: true
  
    - name: Upload screenshots
      uses: actions/upload-artifact@v6
      with:
        name: screenshots
        path: '**/Screenshots/*.png'

    - name: Upload Serilog logs
      uses: actions/upload-artifact@v6
      with:
        name: serilog-logs
        path: '**/Logs/log.txt'
