name: Pipeline to run tests

on:  
  pull_request: 
    branches:  
      - main 
  workflow_dispatch:
    inputs:
        browser:
          description: 'Select browser for tests'
          required: true
          default: 'Chrome'
          type: choice
          options:
            - Chrome
            - Firefox
            - Edge
        skipBddTests:
          type: boolean
          description: 'Skip running BDD tests?'
          default: false
  schedule:
    - cron: '0 1 1 * *'

jobs:  
  build:  
    name: Build and test 
    runs-on: ubuntu-latest 
    env:
      Configuration__BrowserType: Chrome   # Default for pull_request/scheduled
    steps: 
    - name: Checkout code 
      uses: actions/checkout@v6 

    - name: Setup .NET 
      uses: actions/setup-dotnet@v5 
      with:  
        dotnet-version: '8.0.x' 
        
    - name: Set browser from workflow_dispatch input
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: echo "Configuration__BrowserType=${{ github.event.inputs.browser }}" >> $GITHUB_ENV
    
    - name: Log selected browser
      run: echo $Configuration__BrowserType
      
    - name: Log is skipping BDD tests
      run: echo "${{ github.event.inputs.skipBddTests }}"
        
    - name: Install Chrome
      if: ${{ env.Configuration__BrowserType == 'Chrome' }}
      uses: browser-actions/setup-chrome@v2

    - name: Install Firefox
      if: ${{ env.Configuration__BrowserType == 'Firefox' }}
      uses: browser-actions/setup-firefox@v1

    - name: Install Edge
      if: ${{ env.Configuration__BrowserType == 'Edge' }}
      uses: browser-actions/setup-edge@v1

    - name: Restore dependencies 
      run: dotnet restore 
      working-directory: .

    - name: Build 
      run: dotnet build --configuration Release --no-restore 
      working-directory: .

    - name: Run API tests
      run: dotnet test --no-build --configuration Release --verbosity normal --filter "Category=API"
      working-directory: .
      continue-on-error: true
      
    - name: Run NUnit UI tests
      env:
        Configuration__BrowserType: ${{ github.event.inputs.browser }}
        Configuration__Headless: 'true'
      run: dotnet test --no-build --configuration Release --verbosity normal --filter "Category=NUnitUiTests"
      working-directory: .
      continue-on-error: true
      
    - name: Run BDD UI tests
      if: ${{ github.event.inputs.skipBddTests == 'false' }}
      env:
        Configuration__BrowserType: ${{ github.event.inputs.browser }}
        Configuration__Headless: 'true'
      run: dotnet test --no-build --configuration Release --verbosity normal --filter "Category=BddUiTests"
      working-directory: .
      continue-on-error: true
  
    - name: Upload screenshots
      uses: actions/upload-artifact@v6
      with:
        name: screenshots
        path: '**/Screenshots/*.png'

    - name: Upload Serilog logs
      uses: actions/upload-artifact@v6
      with:
        name: serilog-logs
        path: '**/Logs/log.txt'
